<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.protech.nvkids.testcases.bstl.BatchErrorsTestcase" tests="10" time="374.927" ignored="6" failures="3" timestamp="18 Nov 2019 06:23:00 GMT" skipped="0" hostname="probs-165" errors="0">
  <testcase name="TC18_verifyInvalidProcessDate" time="37.826" classname="com.protech.nvkids.testcases.bstl.BatchErrorsTestcase"/>
  <testcase name="TC15_VerifyCharAllowance_NegativeScenario" time="36.741" classname="com.protech.nvkids.testcases.bstl.BatchErrorsTestcase"/>
  <testcase name="TC21_verify_CopyPasteAllowance" time="35.526" classname="com.protech.nvkids.testcases.bstl.BatchErrorsTestcase"/>
  <testcase name="TC14_VerifyCharAllowance_PositiveScenario" time="33.324" classname="com.protech.nvkids.testcases.bstl.BatchErrorsTestcase"/>
  <testcase name="TC19_verifyValidation_VerifyFutureProcessDate" time="37.213" classname="com.protech.nvkids.testcases.bstl.BatchErrorsTestcase"/>
  <testcase name="TC20_verify_NoMatchingRecords" time="40.138" classname="com.protech.nvkids.testcases.bstl.BatchErrorsTestcase"/>
  <testcase name="TC13_verifyfieldspresent" time="54.519" classname="com.protech.nvkids.testcases.bstl.BatchErrorsTestcase">
    <failure type="java.lang.AssertionError" message="The element is not accessible">
      <![CDATA[java.lang.AssertionError: The element is not accessible
	at org.junit.Assert.fail(Assert.java:88)
	at com.protech.selenium.api.base.SeleniumBase.click(SeleniumBase.java:236)
	at com.protech.nvkids.pages.bstl.BatchErrorsPage.verifyFieldsPresent(BatchErrorsPage.java:150)
	at com.protech.nvkids.testcases.bstl.BatchErrorsTestcase.TC13_verifyfieldspresent(BatchErrorsTestcase.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC13_verifyfieldspresent -->
  <testcase name="TC21_verify_SuccessfulInquiry" time="38.963" classname="com.protech.nvkids.testcases.bstl.BatchErrorsTestcase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at com.protech.selenium.api.base.SeleniumBase.VerifyGridHasData(SeleniumBase.java:2285)
	at com.protech.nvkids.pages.bstl.BatchErrorsPage.verifySuccessfulInquiry(BatchErrorsPage.java:206)
	at com.protech.nvkids.testcases.bstl.BatchErrorsTestcase.TC21_verify_SuccessfulInquiry(BatchErrorsTestcase.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC21_verify_SuccessfulInquiry -->
  <testcase name="TC17_verifyNullProcessDate" time="27.495" classname="com.protech.nvkids.testcases.bstl.BatchErrorsTestcase">
    <failure type="java.lang.AssertionError" message="Link not accessible">
      <![CDATA[java.lang.AssertionError: Link not accessible
	at org.junit.Assert.fail(Assert.java:88)
	at com.protech.selenium.api.base.SeleniumBase.clickLink(SeleniumBase.java:312)
	at com.protech.nvkids.pages.bstl.BatchStatusLogsPage.navigatetoBatchErrors(BatchStatusLogsPage.java:80)
	at com.protech.nvkids.testcases.bstl.BatchErrorsTestcase.TC17_verifyNullProcessDate(BatchErrorsTestcase.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC17_verifyNullProcessDate -->
  <testcase name="TC16_VerifyFieldsLength" time="33.182" classname="com.protech.nvkids.testcases.bstl.BatchErrorsTestcase"/>
  <testcase name="stopReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- stopReport -->
  <testcase name="stopReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- stopReport -->
  <testcase name="Deleteimages" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- Deleteimages -->
  <testcase name="Deleteimages" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- Deleteimages -->
  <testcase name="startReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- startReport -->
  <testcase name="startReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- startReport -->
</testsuite> <!-- com.protech.nvkids.testcases.bstl.BatchErrorsTestcase -->
